### PR TITLE
Get ready for Debian 11

### PR DESCRIPTION
**Pull request by smortex**
Debian 11 will be released this week-end.  Debian packages for Puppet 6
and Puppet 7 are already available on the https://apt.puppet.com/
website, we just have to wait for docker images for Debian Bulleye being
tagged `11` to be able to test this release in our CI.

### CODE REVIEW

**Review by bastelfreak — APPROVED** [review]

**Comment by ekohl** [comment]
It looks like https://hub.docker.com/_/debian doesn't have an 11 tag yet. I wonder if we should workaround it in beaker-hostgenerator for now because I'd like to start adding Debian 11 support. In hindsight, there already was a Bullseye tag so we could have done that as soon as the AIO packages were available.

**Comment by ekohl** [comment]
https://github.com/docker-library/official-images/pull/10730 will add the 11 tag to the Bullseye image. Let's wait for that.

**Comment by smortex** [comment]
> It looks like [hub.docker.com/_/debian](https://hub.docker.com/_/debian) doesn't have an 11 tag yet. I wonder if we should workaround it in beaker-hostgenerator for now because I'd like to start adding Debian 11 support. In hindsight, there already was a Bullseye tag so we could have done that as soon as the AIO packages were available.

If I recall correctly when Debian 10 was released no packages have been available for Puppet for a while (Debian was released in July 2019, and I don't see Puppet packages older than October 2019).  It seems to be better this time (but ATM no puppetserver / puppetdb packages seems to be available). I do not know if we can count on it in the future and if the effort is worth it.  Maybe if a "bookworm" directory appears on the apt repository of Puppet we can consider this?

**Comment by ekohl** [comment]
Yes, it would be nice if we can start adding Debian support even before a release is out next time.

**Comment by smortex** [comment]
The 11 tag is now available :tada:

**Review by bastelfreak — APPROVED** [review]

**Pull request merged**
